#!/usr/bin/env bash
#
# Refresh the Paper 1 draft on the website.
#
# The draft is still moving, so it lives in the dissertation repo and is copied
# here on demand rather than kept in sync by hand. This script also stamps the
# PDF's own modification date into _variables.yml, so the "This version" label
# on the Research page can never disagree with the file a reader downloads.
#
#   ./files/src/update-paper.sh            # use the default source path
#   ./files/src/update-paper.sh /some.pdf  # or point it somewhere else
#
# Run it from the repository root, then `quarto render`.

set -euo pipefail

SRC="${1:-/Users/billytulungen/PhD Project/2. paper 1/6. paper/main.pdf}"
DEST="files/paper1-motive-without-mobilization.pdf"

if [[ ! -f "$SRC" ]]; then
  echo "error: source draft not found at:" >&2
  echo "  $SRC" >&2
  exit 1
fi

if [[ ! -d files ]]; then
  echo "error: run this from the repository root (no ./files directory here)" >&2
  exit 1
fi

cp "$SRC" "$DEST"

# Modification date of the PDF itself, not today's date — if the copy is stale
# the label says so.
VERSION=$(date -r "$SRC" "+%-d %B %Y")

cat > _variables.yml <<EOF
# Generated by files/src/update-paper.sh — do not edit by hand.
paper1:
  version: "$VERSION"
EOF

printf 'copied  %s\n' "$DEST"
printf 'version %s\n' "$VERSION"
printf 'now run: quarto render\n'
