#!/usr/bin/env bash
#
# Refresh the Paper 1 draft on the website.
#
# The "This version" label is read from the paper's own title page, not from the
# file's modification date. Those are different things: recompiling an unchanged
# manuscript moves the file date and leaves the title page alone, which once let
# the site advertise a version the download did not support.
#
# Run it from the repository root, then `quarto render`.

set -euo pipefail

SRC="${1:-/Users/billytulungen/PhD Project/2. paper 1/6. paper/main.pdf}"
DEST="files/paper1-motive-without-mobilization.pdf"

if [[ ! -f "$SRC" ]]; then
  echo "error: source draft not found at:" >&2
  echo "  $SRC" >&2
  exit 1
fi

if [[ ! -d files ]]; then
  echo "error: run this from the repository root (no ./files directory here)" >&2
  exit 1
fi

cp "$SRC" "$DEST"

# Modification date of the PDF itself, not today's date — if the copy is stale
# the label says so.

# The date printed on the manuscript, which is what a reader will check.
PDFTOTEXT=$(command -v pdftotext || echo /opt/homebrew/bin/pdftotext)
VERSION=""
if [[ -x "$PDFTOTEXT" ]]; then
  VERSION=$("$PDFTOTEXT" -f 1 -l 1 "$DEST" - 2>/dev/null \
    | sed -n 's/.*[Tt]his version:[[:space:]]*\([^.]*\)\..*/\1/p' | head -1)
fi

if [[ -z "$VERSION" ]]; then
  echo "warning: no \"This version\" line found on the title page." >&2
  echo "         falling back to the file date, which may not match the paper." >&2
  VERSION=$(date -r "$SRC" "+%-d %B %Y")
fi

cat > _variables.yml <<EOF
# Generated by files/src/update-paper.sh — do not edit by hand.
paper1:
  version: "$VERSION"
EOF

printf 'copied  %s\n' "$DEST"
printf 'version %s\n' "$VERSION"
printf 'now run: quarto render\n'
