#!/usr/bin/env bash
#
# Refresh the Paper 1 draft on the website.
#
# WARNING: the stamp below is the PDF file's modification date, which is not the
# same thing as the version printed on the paper's title page. Recompiling an
# unchanged manuscript moves the file date and leaves the title page untouched.
# Check the title page and set the label on research.qmd by hand when they
# differ, or the site will claim a version the download does not support.
#
#
# Run it from the repository root, then `quarto render`.

set -euo pipefail

SRC="${1:-/Users/billytulungen/PhD Project/2. paper 1/6. paper/main.pdf}"
DEST="files/paper1-motive-without-mobilization.pdf"

if [[ ! -f "$SRC" ]]; then
  echo "error: source draft not found at:" >&2
  echo "  $SRC" >&2
  exit 1
fi

if [[ ! -d files ]]; then
  echo "error: run this from the repository root (no ./files directory here)" >&2
  exit 1
fi

cp "$SRC" "$DEST"

# Modification date of the PDF itself, not today's date — if the copy is stale
# the label says so.
VERSION=$(date -r "$SRC" "+%-d %B %Y")

cat > _variables.yml <<EOF
# Generated by files/src/update-paper.sh — do not edit by hand.
paper1:
  version: "$VERSION"
EOF

printf 'copied  %s\n' "$DEST"
printf 'version %s\n' "$VERSION"
printf 'now run: quarto render\n'
